#!/usr/bin/env python3
"""Tests for tools/transcode_video.py - xp3 movies to WebM, in-process.

The tool used to shell out to ffmpeg; it now encodes with PyAV (libvpx-vp9 +
libopus) through rpgmaker.media.  These tests drive the real archive path: a
synthetic .xp3 is built with the repo's own packer, and the source video is
generated by PyAV, so no binary fixture and no external program is involved.

The failure modes that matter for a build: a video that cannot be encoded must
be reported as FAILED (exit code 1) instead of silently missing, a second run
must reuse the finished outputs, and a corrupt entry must not take down the
rest.

Marked `media`: the fixture is a real WMV encoded by PyAV and the assertions
cover a real VP9+Opus round trip, so the PyAV build must carry libvpx-vp9.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "tools"))

import pytest  # noqa: E402

from conftest import make_wmv  # noqa: E402

import transcode_video as tv  # noqa: E402
from kirikiri import xp3pack, xp3tool  # noqa: E402
from rpgmaker import media  # noqa: E402


pytestmark = pytest.mark.media


def make_archive(tmp_path, entries, name="movies.xp3"):
    """Pack `entries` ({relative name: bytes}) into an xp3; returns its path."""
    src = tmp_path / "src"
    src.mkdir(exist_ok=True)
    for rel, data in entries.items():
        path = src / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    archive = str(tmp_path / name)
    xp3pack.pack(str(src), archive)
    return archive


def wmv_bytes(tmp_path, tag="in", **kwargs):
    path = make_wmv(tmp_path / (f"{tag}.wmv"), **kwargs)
    with open(path, "rb") as f:
        return f.read()


class TestCli:
    def test_help_returns_zero(self, capsys):
        assert tv.main(["--help"]) == 0
        assert "Usage:" in capsys.readouterr().out

    def test_missing_argument_is_a_usage_error(self, capsys):
        assert tv.main([]) == 2
        assert "Missing argument" in capsys.readouterr().err

    def test_no_videos_in_the_archive_is_not_a_failure(self, tmp_path,
                                                       capsys):
        archive = make_archive(tmp_path, {"readme.txt": b"nothing to see"})
        out = tmp_path / "out"
        assert tv.main([archive, str(out)]) == 0
        assert "0 video file(s)" in capsys.readouterr().out
        assert os.path.isdir(out)


class TestTranscode:
    def test_extracts_and_encodes_every_video(self, tmp_path, capsys):
        archive = make_archive(tmp_path, {
            "a_ev001a.wmv": wmv_bytes(tmp_path, "a", seconds=0.5),
            "b_ev002b.wmv": wmv_bytes(tmp_path, "b", seconds=0.5),
        })
        out = tmp_path / "out"
        assert tv.main([archive, str(out), "--jobs", "1"]) == 0
        produced = sorted(os.listdir(out))
        assert produced == ["a_ev001a.webm", "b_ev002b.webm"]
        for name in produced:
            path = str(out / name)
            video = media.probe_video(path)
            assert video["codec"] == "vp9"
            assert media.probe(path)["codec"] == "opus"
            assert media.decode_ok(path)[0] is True
        assert "ok" in capsys.readouterr().out

    def test_second_run_reuses_finished_outputs(self, tmp_path, capsys):
        archive = make_archive(tmp_path, {
            "a.wmv": wmv_bytes(tmp_path, "a", seconds=0.5)})
        out = tmp_path / "out"
        tv.main([archive, str(out)])
        before = os.path.getmtime(str(out / "a.webm"))
        capsys.readouterr()
        assert tv.main([archive, str(out)]) == 0
        assert os.path.getmtime(str(out / "a.webm")) == before
        assert "cached" in capsys.readouterr().out

    def test_a_broken_video_fails_loudly_but_does_not_stop_the_others(
            self, tmp_path, capsys):
        archive = make_archive(tmp_path, {
            "good.wmv": wmv_bytes(tmp_path, "good", seconds=0.5),
            "broken.wmv": b"not a video at all",
        })
        out = tmp_path / "out"
        assert tv.main([archive, str(out), "--jobs", "1"]) == 1
        printed = capsys.readouterr().out
        assert "broken" in printed and "FAILED" in printed
        assert os.path.isfile(str(out / "good.webm"))
        assert not os.path.exists(str(out / "broken.webm"))

    def test_non_video_extensions_are_ignored(self, tmp_path):
        archive = make_archive(tmp_path, {
            "a.wmv": wmv_bytes(tmp_path, "a", seconds=0.5),
            "b.mp4": b"pretend mp4",
            "c.png": b"\x89PNG",
        })
        out = tmp_path / "out"
        assert tv.main([archive, str(out), "--jobs", "1"]) == 0
        assert sorted(os.listdir(out)) == ["a.webm"]

    def test_crf_is_forwarded_to_the_encoder(self, tmp_path):
        archive = make_archive(tmp_path, {
            "noisy.wmv": wmv_bytes(tmp_path, "noisy", seconds=0.5, noise=True)})
        low = tmp_path / "low"
        high = tmp_path / "high"
        assert tv.main([archive, str(low), "--crf", "60"]) == 0
        assert tv.main([archive, str(high), "--crf", "0"]) == 0
        assert os.path.getsize(str(low / "noisy.webm")) < \
            os.path.getsize(str(high / "noisy.webm"))

    def test_missing_archive_is_an_error_not_a_traceback(self, tmp_path):
        with pytest.raises(OSError):
            tv.main([str(tmp_path / "nope.xp3"), str(tmp_path / "out")])


class TestOffline:
    def test_no_ffmpeg_is_needed(self):
        """The point of the rewrite: the module must not resolve or run any
        external encoder."""
        import inspect

        source = inspect.getsource(tv)
        assert "find_ffmpeg" not in source
        assert "proctools" not in source
        assert "subprocess" not in source


class TestTranscodeOne:
    def test_returns_a_status_tuple_per_entry(self, tmp_path):
        archive = make_archive(tmp_path, {
            "a.wmv": wmv_bytes(tmp_path, "a", seconds=0.5)})
        out = tmp_path / "out"
        out.mkdir()
        entry = xp3tool.open_xp3(archive)[0]
        name, size, elapsed, status = tv.transcode_one(
            entry, archive, str(out), 32, 4)
        assert (name, status) == ("a", "ok")
        assert size == os.path.getsize(str(out / "a.webm"))
        assert elapsed >= 0
