"""TJS2 -> JavaScript converter for KAG3 [iscript] blocks.

KiriKiri iscript blocks are TJS2, but TyranoScript executes [iscript]
with JavaScript eval. This module converts the TJS2 dialect constructs
actually used by KAG3 games into equivalent JS:

- `%[key:value, ...]` dict literals -> JS object literals
- `"str".sprintf(args)` -> shimmed String.prototype.sprintf (runtime)
- `class X { var a; function F{...} }` -> JS prototype-based classes
  (fields collected, methods become prototypes, TJS property
  getter/setter blocks become JS get/set accessors)
- bare field references inside class methods -> this.field
- TJS string concatenation `&` -> `+` (inside converted regions)
- `kag.se[0].setOptions(...)` etc: KAG runtime calls are left intact;
  the runtime shim (generated by convert_kag.py) provides them.
"""

import re

SPRINTF_SHIM = """
// TJS2 String#sprintf shim (subset: %d %s %02d %03d width flags)
if (!String.prototype.sprintf) {
    String.prototype.sprintf = function () {
        var args = Array.prototype.slice.call(arguments);
        var i = 0;
        return this.replace(/%([0-9]+)?([ds])/g, function (m, width, type) {
            var v = args[i++];
            if (type === 'd') { v = Math.floor(Number(v) || 0); }
            else { v = String(v); }
            if (width) {
                var w = Number(width);
                if (type === 'd') {
                    var neg = v < 0;
                    var s = String(Math.abs(v));
                    while (s.length < w) { s = '0' + s; }
                    v = (neg ? '-' : '') + s;
                } else {
                    while (String(v).length < w) { v = ' ' + v; }
                }
            }
            return v;
        });
    };
}
"""


def convert_dict_literals(text):
    """%[k1:v1, k2:v2] -> {k1:v1, k2:v2} (TJS dictionary literal)."""
    def repl(m):
        body = m.group(1)
        pairs = []
        for part in _split_top(body):
            if ":" not in part:
                pairs.append(part.strip())
                continue
            k, v = part.split(":", 1)
            k = k.strip()
            if re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', k):
                pairs.append("%s: %s" % (k, v.strip()))
            else:
                pairs.append("%r: %s" % (k, v.strip()))
        return "{" + ", ".join(pairs) + "}"
    return re.sub(r"%\[(.*?)\]", repl, text, flags=re.S)


def _split_top(s):
    """Split on top-level commas (ignore nested brackets/parens/strings)."""
    parts = []
    depth = 0
    cur = []
    i = 0
    n = len(s)
    quote = None
    while i < n:
        c = s[i]
        if quote:
            cur.append(c)
            if c == quote and s[i - 1] != "\\":
                quote = None
        elif c in "'\"":
            quote = c
            cur.append(c)
        elif c in "([{":
            depth += 1
            cur.append(c)
        elif c in ")]}":
            depth -= 1
            cur.append(c)
        elif c == "," and depth == 0:
            parts.append("".join(cur).strip())
            cur = []
        else:
            cur.append(c)
        i += 1
    if cur:
        parts.append("".join(cur).strip())
    return parts


def convert_sprintf(text):
    """\"%02d\".sprintf(x) -> sprintf shim call (String.prototype.sprintf)."""
    return re.sub(
        r'("(?:[^"\\]|\\.)*")\.sprintf\s*\((.*?)\)',
        lambda m: "%s.sprintf(%s)" % (m.group(1), m.group(2)),
        text,
        flags=re.S,
    )


def convert_concat(text):
    """TJS string concat `a & b` -> `a + b`.

    Only inside converted iscript bodies; `&` in bitwise contexts or
    logical contexts (&&, &=) is preserved.
    """
    out = []
    i = 0
    n = len(text)
    while i < n:
        c = text[i]
        if c == "&":
            nxt = text[i + 1] if i + 1 < n else ""
            if nxt in "&=":
                out.append(c)
                out.append(nxt)
                i += 2
                continue
            # plain binary & -> string concat (TJS semantics)
            out.append("+")
            i += 1
            continue
        out.append(c)
        i += 1
    return "".join(out)


def _collect_brace_block(text, start):
    """Given text and index of '{', return (inner, end_index_after_})."""
    depth = 0
    i = start
    n = len(text)
    quote = None
    while i < n:
        c = text[i]
        if quote:
            if c == quote and text[i - 1] != "\\":
                quote = None
        elif c in "'\"":
            quote = c
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:i], i + 1
        i += 1
    return text[start + 1:], n


def convert_classes(text):
    """Convert TJS2 class blocks to JS prototype classes (robust line scan).

    Handles the TJS2 forms actually used by KAG3 games:
        class Foo {
            var a;
            var b = 0;
            function Foo(x) { ... }      // ctor (name == class, may lack ())
            function bar(y) { ... }
            property p { getter { ... } setter(v) { ... } }
        }
    """
    out = []
    pos = 0
    for m in re.finditer(r"\bclass\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{", text):
        out.append(text[pos:m.start()])
        name = m.group(1)
        inner, end = _collect_brace_block(text, m.end() - 1)
        fields = []      # (fname, fvalue)
        ctor_body = []
        methods = []     # (fname, params, body_lines)
        props = []       # (pname, getter_lines, setter_params, setter_lines)

        # tokenize inner into top-level blocks by brace depth
        blocks = _split_blocks(inner)
        for blk in blocks:
            blk = blk.strip()
            if not blk:
                continue
            fm = re.match(r"var\s+([A-Za-z_][A-Za-z0-9_]*)(\s*=\s*(.*?))?\s*;?$", blk, re.S)
            if fm:
                fval = (fm.group(3) or "").strip() or "undefined"
                if "//" in fval:
                    fval = fval.split("//", 1)[0].strip() or "undefined"
                fields.append((fm.group(1), fval))
                continue
            fmm = re.match(r"function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(?([^(){}]*)\)?\s*", blk, re.S)
            if fmm:
                fname = fmm.group(1)
                params = fmm.group(2).strip()
                body = blk[fmm.end():].strip()
                if body.startswith("{"):
                    body = body[1:]
                if body.endswith("}"):
                    body = body[:-1]
                if fname == name:
                    ctor_body = body.splitlines()
                else:
                    methods.append((fname, params, body.splitlines()))
                continue
            pmm = re.match(r"property\s+([A-Za-z_][A-Za-z0-9_]*)\s*", blk, re.S)
            if pmm:
                pname = pmm.group(1)
                pbody = blk[pmm.end():].strip()
                if pbody.startswith("{"):
                    pbody = pbody[1:]
                if pbody.endswith("}"):
                    pbody = pbody[:-1]
                gmm = re.search(r"getter\s*\(?[^()]*\)?\s*\{(.*)\}", pbody, re.S)
                getter = gmm.group(1) if gmm else None
                smm = re.search(r"setter\s*\(([^)]*)\)\s*\{(.*)\}", pbody, re.S)
                setter = (smm.group(1).strip(), smm.group(2)) if smm else None
                props.append((pname, getter, setter))
                continue
            # unrecognized top-level chunk: append to ctor body (safety)
            ctor_body.extend(blk.splitlines())

        fieldnames = [f[0] for f in fields]
        lines = ["function %s() {" % name]
        for fname, fval in fields:
            lines.append("    this.%s = %s;" % (fname, fval))
        for cl in ctor_body:
            lines.append("    " + _fieldref(fieldnames, cl.strip()))
        lines.append("}")
        out.append("\n".join(lines))
        for fname, params, body_lines in methods:
            body = "\n".join(_fieldref(fieldnames, ln) for ln in body_lines)
            out.append("%s.prototype.%s = function (%s) {" % (name, fname, params))
            out.append(body)
            out.append("};")
        for pname, getter, setter in props:
            d = ["Object.defineProperty(%s.prototype, %r, {" % (name, pname)]
            if getter is not None:
                d.append("    get: function () {")
                d.append("\n".join(_fieldref(fieldnames, ln) for ln in getter.splitlines()))
                d.append("    },")
            if setter is not None:
                sparam, sbody = setter
                d.append("    set: function (%s) {" % sparam)
                d.append("\n".join(_fieldref(fieldnames, ln) for ln in sbody.splitlines()))
                d.append("    },")
            d.append("});")
            out.append("\n".join(d))
        pos = end
    out.append(text[pos:])
    return "".join(out)


def _split_blocks(text):
    """Split class body into top-level units.

    Units are either a `var x[=v];` declaration, a `function name...{...}`
    block, a `property name{...}` block, or leftover text. Brace-pairing
    scan so `function Foo` and `{` may be on separate lines (TJS2 allows
    `function Foo` with no parens).
    """
    units = []
    i = 0
    n = len(text)
    while i < n:
        # skip whitespace
        while i < n and text[i] in " \t\r\n":
            i += 1
        if i >= n:
            break
        # var declaration (ends at ;)
        m = re.match(r"var\s+([A-Za-z_][A-Za-z0-9_]*)(.*?);", text[i:], re.S)
        if m and not text[i:].lstrip().startswith("var ") or m and m.start() == 0:
            pass
        if re.match(r"var\s+[A-Za-z_]", text[i:]):
            m = re.match(r"var\s+[A-Za-z_][A-Za-z0-9_]*(?:\s*=\s*.*?)?;", text[i:], re.S)
            if m:
                units.append(m.group(0))
                i += m.end()
                continue
        # function or property block
        m = re.match(r"(function\s+[A-Za-z_][A-Za-z0-9_]*\s*\(?[^(){]*\)?|property\s+[A-Za-z_][A-Za-z0-9_]*)", text[i:], re.S)
        if m:
            head = m.group(0)
            j = i + m.end()
            while j < n and text[j] in " \t\r\n":
                j += 1
            if j < n and text[j] == "{":
                inner, end = _collect_brace_block(text, j)
                units.append(head + "{" + inner + "}")
                i = end
                continue
            # function without body: keep head
            units.append(head)
            i = i + m.end()
            continue
        # leftover chunk up to next var/function/property
        m = re.search(r"(?=\b(?:var|function|property)\s+)", text[i:])
        if m:
            units.append(text[i:i + m.start()])
            i += m.start()
        else:
            units.append(text[i:])
            break
    return units



def _fieldref(fields, body):
    """Prefix bare field references inside a method body with `this.`."""
    for f in fields:
        body = re.sub(
            r"(?<![\w.])%s(?![\w])" % re.escape(f),
            "this.%s" % f,
            body,
        )
    return body


def convert_iscript(text):
    """Convert a whole [iscript] block body (TJS2 -> JS)."""
    text = convert_dict_literals(text)
    text = convert_sprintf(text)
    text = convert_concat(text)
    text = convert_classes(text)
    text = convert_count(text)
    return text


def convert_count(text):
    """TJS array `.count` -> JS `.length` (TJS arrays expose count)."""
    return re.sub(r"(?<=\.)count(?![\w])", "length", text)


def convert_casts(text):
    """TJS2 (int)/(real) type casts -> JS Math.floor/Number.

    `(int)expr` and `(real)expr` appear in KAG3 eval expressions; they are
    syntax errors in JS. (int) truncates, (real) is a no-op for numbers.
    """
    # (int)expr -> Math.floor(expr); handle (int)(expr) and (int)expr
    text = re.sub(r"\(int\)\s*\(([^()]*)\)", r"Math.floor(\1)", text)
    text = re.sub(r"\(int\)\s*([\w.]+)", r"Math.floor(\1)", text)
    text = re.sub(r"\(real\)\s*\(", "Number(", text)
    text = re.sub(r"\(real\)\s*([\w.]+)", r"Number(\1)", text)
    return text


def convert_backslash_div(text):
    """TJS2 integer division backslash -> Math.floor(a / b)."""
    return re.sub(r"(\b[\w.\[\]]+)\\(\b[\w.\[\]]+)", r"Math.floor(\1 / \2)", text)


def convert_amp_ref(text):
    """TJS2 leading & (function/object reference) -> plain expression.

    `&f.xxx` / `&func(...)` reference forms; in JS they can be dropped
    (member access and calls already work without the &).
    """
    return re.sub(r"&(?!&)(?=[\w\[])", "", text)


def convert_incontextof(text):
    """TJS2 `function {...} incontextof this` -> plain block."""
    return re.sub(r"\s+incontextof\s+[\w.]+", "", text)


def convert_expr(text):
    """Convert TJS2 expressions used in [eval]/[if]/cond attributes."""
    text = convert_dict_literals(text)
    text = convert_sprintf(text)
    text = convert_count(text)
    text = convert_casts(text)
    text = convert_backslash_div(text)
    text = convert_amp_ref(text)
    text = convert_incontextof(text)
    return text
