"""The JS/CSS injected into the converted project (shim layer, pass 5).

The shim text lives in `js/` as real files rather than as 800-line string
literals: whole shims (`fast_skip.js`, `noop_plus_real.js`, `video_shim.js`,
`waitskip_shim.js`, `map_engine.js`, `portrait.css`) plus `runtime_shim.js`, a
template that pulls three of them in at its `__KAG3_INCLUDE:<NAME>__` markers
(the assembly order is part of the generated output, so the markers keep that
order visible in the file instead of hiding it in Python string concatenation).

`_shim_js()` builds the per-game no-op plugin: one `define("<tag>")` per
KAG3-only tag Tyrano does not implement, each carrying the intent note from
``tags.tag_intent()``.  Tags that got a real implementation (VIDEO_TAGS) are
excluded on purpose -- registering a no-op over a real tag is the silent
breakage documented in `docs/kirikiri-tyrano.md` §4.4.
"""
import logging
from importlib import resources

from kirikiri.kag.tags import (SHIM_TAG_NAMES, VIDEO_TAGS, engine_tag_names,
                               tag_intent)

log = logging.getLogger(__name__)


def _decode_shim(data, name):
    """Validate and decode one shim asset's bytes.

    The assets end with exactly one newline (editors and git prefer it); the
    generated output must not, so exactly one is dropped here.  LF only: the
    generated JS/CSS is compared byte-for-byte against the pre-split output,
    so a CRLF file (a Windows editor writing one) must fail loudly instead of
    leaking \\r into every converted build.
    """
    text = data.decode("utf-8")
    if "\r" in text:
        raise ValueError(f"shim asset {name} must use LF line endings")
    if text.endswith("\n"):
        text = text[:-1]
    return text


def _shim_text(name):
    """Read one shim asset (`js/<name>`) shipped with this package."""
    blob = resources.files(__package__).joinpath("js", name).read_bytes()
    return _decode_shim(blob, name)


def _assemble(name, pieces):
    """Expand the ``__KAG3_INCLUDE__`` markers of one shim template."""
    text = _shim_text(name)
    for marker_name, value in pieces:
        marker = f"// __KAG3_INCLUDE:{marker_name}__"
        if marker not in text:
            raise ValueError(f"shim template {name} lost its {marker_name} marker")
        text = text.replace(marker, value)
    return text


#: One source file per generated artifact; `_shim_text` drops the final newline.
FAST_SKIP_SHIM_JS = _shim_text("fast_skip.js")
NOOP_PLUS_REAL_JS = _shim_text("noop_plus_real.js")
VIDEO_SHIM_JS = _shim_text("video_shim.js")
WAITSKIP_SHIM_JS = _shim_text("waitskip_shim.js")
MAP_ENGINE_JS = _shim_text("map_engine.js")
PORTRAIT_CSS = _shim_text("portrait.css")
RUNTIME_SHIM_IIFE = _assemble("runtime_shim.js", (
    ("WAITSKIP_SHIM_JS", WAITSKIP_SHIM_JS),
    ("VIDEO_SHIM_JS", VIDEO_SHIM_JS),
    ("MAP_ENGINE_JS", MAP_ENGINE_JS),
))


def _shim_js(macros=(), engine_dir=None, used_tags=None, usage=None):
    """Generate the plugin js registering KAG3-only tags as no-ops.

    Only tags that TyranoScript does not implement AND are not game-defined
    macros get shimmed: if a game macro name were registered here it would
    shadow the macro (Tyrano checks master_tag before map_macro) and the
    macro body would never run.
    """
    macros = {m.lower() for m in macros}
    # Tags with a real implementation below must NOT also be registered as
    # no-ops (a later registration would win and the feature would silently
    # disappear).
    real = set(VIDEO_TAGS)
    engine_tags = engine_tag_names(engine_dir) if engine_dir else set()
    # Anything the corpus uses that neither the engine nor a game macro provides
    # gets a no-op too, so a missing tag can never raise Tyrano's blocking
    # alert(). SHIM_TAG_NAMES alone is a hand-written list and missed names
    # (measured: [style] with 59 call sites).
    candidates = set(SHIM_TAG_NAMES) | {t.lower() for t in (used_tags or set())}
    names = [n for n in sorted(candidates)
             if n.lower() not in macros and n.lower() not in real
             and n.lower() not in engine_tags]
    lines = [
        "// Auto-generated by convert_kag.py: KAG3-only tags as no-ops.",
        "// Ensures scenarios do not hit TyranoScript's undefined_tag error.",
        "// A name the engine implements is NEVER registered here.",
        "(function () {",
        "  var noop = function (pm) { this.kag.ftag.nextOrder(); };",
        "  window.__kag3_shim_skipped = [];",
        "  var define = function (name) {",
        "    // runtime guard: the engine wins, whoever registered first",
        "    if (tyrano.plugin.kag.tag[name]) {",
        "      window.__kag3_shim_skipped.push(name);",
        "      return;",
        "    }",
        "    tyrano.plugin.kag.tag[name] = { start: noop };",
        "  };",
    ]
    for name in sorted(names):
        rec = (usage or {}).get(name.lower()) or {}
        attrs = sorted((rec.get("attrs") or {}).keys())
        lines.append("")
        lines.append("  // [%s] -- KAG3 tag, NOT implemented by TyranoScript: "
                     "%d call site(s)." % (name, rec.get("count", 0)))
        if attrs:
            lines.append("  //   arguments seen: {}".format(", ".join(attrs[:12])))
        lines.extend(f"  //   example: {ex}"
                     for ex in (rec.get("examples") or [])[:2])
        lines.append(f"  //   INTENT: {tag_intent(name, usage or {})}")
        lines.append(f'  define("{name}");')
    lines.append(NOOP_PLUS_REAL_JS)
    return "\n".join(lines) + "\n", len(names)
