#!/usr/bin/env python3
"""unlock_gallery.py - OPTIONAL workflow: unlock a game's CG gallery / recall room.

Analysis
  - Finds the gallery map via MapInfos.json names (回想 / ギャラリー / アルバム /
    CG / 思い出 / gallery / album / ...).
  - Scans the gallery map's event page conditions and picks the "unlock-all"
    switch: the switch gating the most gallery entries, preferring a name that
    contains 開放 / 解放 / unlock / open / all / 全. Only switches that appear
    as page conditions NOWHERE outside the gallery maps are eligible - forcing
    a switch that gates normal gameplay would break it.
  - Some games have NO such flag at all (per-CG switches only, or a plugin /
    save-based gallery). In that case the tool reports and does nothing - do
    not invent a flag.

Action
  - Writes js/plugins/GalleryUnlock.js: on boot (new game AND every save load)
    it sets the unlock switch(es) ON, then registers the plugin in js/plugins.js.
  - Remove the plugin file + entry to restore normal unlock behavior.

Usage
  python unlock_gallery.py <web_root> [--switches 45,1] [--dry-run] [--plugin GalleryUnlock]
"""
import json
import logging
import os
import re
import sys
from typing import Annotated

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))  # repo root: rpgmaker/
sys.path.insert(0, _HERE)                   # sibling tools: plain_io
import plain_io  # noqa: E402
from rpgmaker import cliutil  # noqa: E402

log = logging.getLogger("unlock_gallery")

GALLERY_MAP_RE = re.compile(
    r"回想|ギャラリ|アルバム|思い出|思いで|CG|gallery|album|replay|回忆|画廊|相册", re.I)
UNLOCK_NAME_RE = re.compile(
    r"開放|解放|解禁|公開|全|unlock|open|all|开放|解锁", re.I)
GALLERY_NAME_RE = re.compile(r"回想|ギャラリ|アルバム|gallery|album|回忆|画廊|相册", re.I)

PLUGIN_TEMPLATE = """\
//=============================================================================
// {plugin}.js - unlock gallery / recall-room entries (generated by unlock_gallery.py)
//=============================================================================
/*:
 * @plugindesc v1.0.0 Sets gallery unlock switch(es) ON on boot
 * @author GameTranslation (unlock_gallery.py)
 * @help
 * Sets the configured game switches ON every boot (new game and each save
 * load), which unlocks the game's CG gallery / recall-room entries.
 *
 * Generated for "{title}" by tools/unlock_gallery.py.
 * Delete this file and its js/plugins.js entry to restore normal unlocks.
 */
(function() {{
    'use strict';
    var SWITCHES = [{switches}];
    function setSwitches() {{
        for (var i = 0; i < SWITCHES.length; i++) {{
            $gameSwitches.setValue(SWITCHES[i], true);
        }}
    }}
    var _createGameObjects = DataManager.createGameObjects;
    DataManager.createGameObjects = function() {{
        _createGameObjects.call(this);
        setSwitches();
    }};
    var _extractSaveContents = DataManager.extractSaveContents;
    DataManager.extractSaveContents = function(contents) {{
        _extractSaveContents.call(this, contents);
        setSwitches();
    }};
}})();
"""


def game_title(web_root):
    try:
        s = plain_io.load_json(os.path.join(web_root, "data", "System.json"))
        return s.get("gameTitle") or os.path.basename(web_root)
    except (OSError, ValueError):
        # OSError: file I/O; ValueError: JSONDecodeError/UnicodeDecodeError on
        # custom-encrypted System.json -> degrade to the folder name.
        return os.path.basename(web_root)


def switch_names(web_root):
    try:
        s = plain_io.load_json(os.path.join(web_root, "data", "System.json"))
        return dict(enumerate(s.get("switches") or []))
    except (OSError, ValueError):
        return {}


def find_gallery_maps(web_root):
    """Return [mapId] whose displayName matches gallery-ish names."""
    path = os.path.join(web_root, "data", "MapInfos.json")
    if not os.path.isfile(path):
        return []
    try:
        infos = plain_io.load_json(path)
    except (OSError, ValueError):
        return []
    cands = []
    for m in infos:
        if isinstance(m, dict) and m.get("name"):
            name = m["name"]
            # "h " prefix is the common adult-scene map convention - not a gallery
            if re.match(r"^(h|H|ｈ|H)\s|^h\s", name):
                continue
            if GALLERY_MAP_RE.search(name):
                cands.append((m.get("id"), name))
    cands.sort(key=lambda t: 0 if GALLERY_NAME_RE.search(t[1]) else 1)
    return cands


def scan_page_switches(web_root, map_id):
    """Count page-condition switch usage on a map. Returns
    {switchId: {'events': set, 'pages': n}} and the set of events present."""
    path = os.path.join(web_root, "data", "Map%d.json" % map_id)
    if not os.path.isfile(path):
        return {}, set()
    try:
        d = plain_io.load_json(path)
    except (OSError, ValueError):
        return {}, set()
    usage = {}
    events = set()
    for ev in d.get("events") or []:
        if not isinstance(ev, dict):
            continue
        events.add(ev.get("id"))
        for pg in ev.get("pages") or []:
            if not isinstance(pg, dict):
                continue
            cond = pg.get("conditions") or {}
            for key in ("switch1", "switch2"):
                if cond.get(key + "Valid") and isinstance(cond.get(key + "Id"), int):
                    u = usage.setdefault(cond[key + "Id"], {"events": set(), "pages": 0})
                    u["events"].add(ev.get("id"))
                    u["pages"] += 1
    return usage, events


def scan_global_switch_conditions(web_root, exclude_map_ids):
    """Switch ids used as page conditions on ANY map outside the gallery."""
    used = set()
    for fn in os.listdir(os.path.join(web_root, "data")):
        if not (fn.startswith("Map") and fn.endswith(".json")):
            continue
        mid = fn[3:-5]
        if not mid.isdigit():
            continue
        if int(mid) in exclude_map_ids:
            continue
        usage, _ = scan_page_switches(web_root, int(mid))
        used.update(usage)
    return used


def pick_unlock_switches(web_root, gallery_maps, dry_run):
    """Choose the unlock-all switch(es). Returns (switch_ids, report_lines)."""
    names = switch_names(web_root)
    report = []
    exclude = {mid for mid, _ in gallery_maps}
    unsafe = scan_global_switch_conditions(web_root, exclude)
    chosen = []
    for mid, mname in gallery_maps:
        usage, _ = scan_page_switches(web_root, mid)
        report.append("gallery map %d (%s): %d switch conditions"
                      % (mid, mname, sum(u["pages"] for u in usage.values())))
        cands = []
        for sw, u in usage.items():
            if sw in unsafe:
                report.append("  switch %d (%s): skip - also gates %d events outside the gallery"
                              % (sw, names.get(sw, ""), len(u["events"])))
                continue
            cands.append((u["pages"], u["events"], sw))
        if not cands:
            continue
        cands.sort(key=lambda t: (-t[0], -len(t[1])))
        best = cands[0][2]
        # prefer a name that smells like "unlock all"
        for _p, _e, sw in cands:
            if UNLOCK_NAME_RE.search(names.get(sw, "")):
                best = sw
                break
        chosen.append(best)
        report.append("  unlock-all switch: %d (%s)" % (best, names.get(best, "")))
        for _p, evs, sw in cands[:5]:
            if sw != best:
                report.append("    alt: %d (%s) gates %d events"
                              % (sw, names.get(sw, ""), len(evs)))
    if not chosen:
        report.append("NO unlock-all switch found - this game likely unlocks the gallery "
                      "per-entry or via a plugin/save. Nothing to patch; keep the original "
                      "unlock mechanics.")
    return chosen, report


def build_plugin_js(switches, title, plugin_name):
    return PLUGIN_TEMPLATE.format(
        plugin=plugin_name,
        title=title.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " "),
        switches=",".join(str(s) for s in sorted(switches)))


def register_plugin(web_root, plugin_name, description):
    """Append {"name": plugin_name, ...} to the $plugins array in js/plugins.js."""
    path = os.path.join(web_root, "js", "plugins.js")
    if not os.path.isfile(path):
        return False
    with open(path, encoding="utf-8-sig") as f:
        text = f.read()
    m = re.search(r"\$plugins\s*=\s*(\[.*?\])\s*;", text, re.S)
    if not m:
        log.warning("js/plugins.js has no $plugins array; plugin file written but not registered")
        return False
    plugins = json.loads(m.group(1))
    plugins = [p for p in plugins if p.get("name") != plugin_name]
    plugins.append({"name": plugin_name, "status": True, "description": description,
                    "parameters": {}})
    new_text = text[:m.start(1)] + json.dumps(plugins, ensure_ascii=False) + text[m.end(1):]
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(new_text)
    return True


def cmd(web_root: Annotated[str, cliutil.Argument(
            help="game web root (JoiPlay build)")],
        switches: Annotated[str, cliutil.Option(
            "--switches", help="explicit unlock switch ids (comma-separated), "
            "skip detection")] = "",
        dry_run: Annotated[bool, cliutil.Option(
            "--dry-run", help="report only, write nothing")] = False,
        plugin: Annotated[str, cliutil.Option(
            "--plugin", help="plugin file name")] = "GalleryUnlock",
        verbose: cliutil.Verbose = False,
        quiet: cliutil.Quiet = False,
        log_file: cliutil.LogFile = None) -> int:
    cliutil.setup_logging(verbose, quiet, log_file)
    # Single gate for every path this command touches, before the
    # first stat/open/mkdir (AGENTS.md CRITICAL cross-system rule).
    cliutil.own_paths("unlock gallery", web_root=web_root)
    root = os.path.abspath(web_root)
    if not os.path.isfile(os.path.join(root, "index.html")):
        print(f"not a web root: {root}", file=sys.stderr)
        return 1

    if switches:
        switch_ids = [int(x) for x in switches.split(",") if x.strip()]
        names = switch_names(root)
        report = ["explicit switches: " + ", ".join(
            "%d (%s)" % (s, names.get(s, "")) for s in switch_ids)]
    else:
        gallery_maps = find_gallery_maps(root)
        report = ["gallery maps found: %s" % (gallery_maps or "NONE")]
        if not gallery_maps:
            log.info("\n".join(report))
            return 0
        switch_ids, extra = pick_unlock_switches(root, gallery_maps, dry_run)
        report += extra
        if not switch_ids:
            log.info("\n".join(report))
            return 0

    log.info("\n".join(report))

    if dry_run:
        log.info("dry-run: no files written")
        return 0
    if not switch_ids:
        return 0

    title = game_title(root)
    js = build_plugin_js(switch_ids, title, plugin)
    plugin_dir = os.path.join(root, "js", "plugins")
    os.makedirs(plugin_dir, exist_ok=True)
    plugin_path = os.path.join(plugin_dir, plugin + ".js")
    with open(plugin_path, "w", encoding="utf-8", newline="") as f:
        f.write(js)
    desc = "Unlock gallery entries (switches {}) - generated by unlock_gallery.py".format(",".join(str(s) for s in switch_ids))
    ok = register_plugin(root, plugin, desc)
    log.info("wrote %s (switches %s), registered=%s",
             plugin_path, switch_ids, ok)
    return 0


app = cliutil.command_app(cmd, help=__doc__)
# argparse used the module docstring as the command description; keep that
# visible in --help (a collapsed single-command app shows the command help).
cmd.__doc__ = __doc__


def main(argv=None) -> int:
    return cliutil.run(app, argv, prog="unlock_gallery.py")


if __name__ == "__main__":
    raise SystemExit(main())
