// KAG3 runtime shims for TyranoScript (generated by convert_kag.py)
window.__missing_tags = window.__missing_tags || [];
window.Debug = window.Debug || { message: function () {} };
(function () {
// __KAG3_INCLUDE:WAITSKIP_SHIM_JS__
// __KAG3_INCLUDE:VIDEO_SHIM_JS__
// KAG3 [s] -> [kag3stop]: pure stop. Registered at parse time like
// kagwaitskip (boot copies tyrano.plugin.kag.tag into master_tag).
// KAG3's [s] parks the scenario (inSleep=true, no click callback) and
// the flow resumes only via window.process()/jump/links/maps; a plain
// click must NOT advance it (dead-zone clicks on the title do nothing).
// Strong stop + hidden event layer make Tyrano clicks inert; the map
// engine's document-capture listener, [link] spans and [jump] all work
// independently of the flow state.
tyrano.plugin.kag.tag['kag3stop'] = {
  start: function (pm) {
    this.kag.weaklyStop();
    this.kag.stronglyStop();
    try { this.kag.layer.hideEventLayer(); } catch (e) {}
  },
};
// KAG3 [ch text="..."] renders text on the current message layer with
// the current font settings (names, choice labels, menu items all use
// it via macros). Tyrano's text tag does the same and calls nextOrder
// itself when the typewriter finishes, so this shim must NOT advance.
tyrano.plugin.kag.tag['ch'] = {
  start: function (pm) {
    if (window.__kag3_prepare_message) window.__kag3_prepare_message(this.kag);
    var p = { val: pm.text === undefined ? '' : String(pm.text) };
    if (pm.p !== undefined) p.p = pm.p;
    if (pm.size !== undefined) p.size = pm.size;
    if (pm.color !== undefined) p.color = pm.color;
    if (pm.face !== undefined) p.face = pm.face;
    this.kag.ftag.startTag('text', p);
  },
};
// __KAG3_INCLUDE:MAP_ENGINE_JS__
// Click lock: the click that triggers a scene change must not be consumed a
// second time by the screen it just opened.  KAG3 jumps run synchronously, so
// the same DOM event finishes bubbling after the new screen has armed its own
// clickable map / [p] wait - the gallery then opened the entry the pointer
// happened to land on (owner: "进画廊后，会自动点第一个 CG 鉴赏") and a replay
// lost its first line (owner: "进回想以后，第一句话会被自动跳过").
// A jump/call arms a short window during which clicks are swallowed in the
// capture phase, so no later handler sees a click that belonged to the
// previous screen.  Registered before the map engine's own hook (which is
// installed lazily on the first [mapaction]) so the guard runs first.
window.__kag3_click_lock_until = 0;
var __kag3_lock_clicks = function (ms) {
  window.__kag3_click_lock_until = Date.now() + (ms || 300);
};
document.addEventListener('click', function (e) {
  if (Date.now() < window.__kag3_click_lock_until) {
    e.stopPropagation();
    e.stopImmediatePropagation();
    if (e.preventDefault) e.preventDefault();
  }
}, true);
// Bubble-phase twin: a jump that started from inside this same click already
// passed the capture guard, so the event must not reach later handlers either.
document.addEventListener('click', function (e) {
  if (Date.now() < window.__kag3_click_lock_until) {
    e.stopPropagation();
    e.stopImmediatePropagation();
  }
}, false);
document.addEventListener('mousedown', function (e) {
  if (Date.now() < window.__kag3_click_lock_until) {
    e.stopPropagation();
    e.stopImmediatePropagation();
  }
}, true);
(function () {
  var T = tyrano.plugin.kag.tag;
  ['jump', 'call'].forEach(function (name) {
    var t = T[name];
    if (!t || !t.start || t.__kag3_click_lock) return;
    t.__kag3_click_lock = true;
    var orig = t.start;
    t.start = function (pm) {
      __kag3_lock_clicks(300);
      // The new scene must not inherit half-satisfied click state from the
      // click that got us here (Tyrano clears weak stops on click, so a
      // pending one otherwise consumes the new screen's first [p]/[s]).
      try {
        this.kag.cancelWeakStop();
        this.kag.stat.is_click_text = false;
      } catch (e) {}
      return orig.apply(this, arguments);
    };
  });
})();
// ---------------------------------------------------------------------------
// In-game menu overlay.
//
// KAG3 ships a built-in system menu: the game arms it with a plain
// [rclick enabled=true] (newgame.ks:26 etc.) and KAG3 opens its own menu on
// right-click.  This port has no engine menu (the shim used to register the
// default rclick as a no-op), so in-story there was nothing to open - the owner
// had no way back to the main menu.  The overlay below is that menu: entries are
// added from the build knobs (window.__kag3_title_jump carries the game's own
// title storage/label, which is game data and therefore never hardcoded here).
var __kag3_menu_el = null;
var __kag3_menu_close = function () {
  if (__kag3_menu_el && __kag3_menu_el.parentNode) {
    __kag3_menu_el.parentNode.removeChild(__kag3_menu_el);
  }
  __kag3_menu_el = null;
};
var __kag3_menu_is_open = function () { return !!__kag3_menu_el; };
var __kag3_menu_open = function () {
  __kag3_menu_close();
  var kag = window.TYRANO && TYRANO.kag;
  if (!kag) return;
  var tj = window.__kag3_title_jump || {};
  var box = document.createElement('div');
  box.setAttribute('data-kag3', 'sysmenu');
  box.style.cssText = 'position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);' +
    'z-index:2147483001;min-width:240px;padding:16px 18px;border-radius:12px;' +
    'background:rgba(5,8,14,.94);border:1px solid rgba(255,255,255,.35);' +
    'box-shadow:0 18px 48px rgba(0,0,0,.6);color:#fff;' +
    'font:600 15px/1.5 system-ui,sans-serif;text-align:center';
  var title = document.createElement('div');
  title.textContent = '菜单';
  title.style.cssText = 'margin:0 0 12px;opacity:.75;font-size:13px;letter-spacing:.08em';
  box.appendChild(title);
  var add = function (label, fn, primary) {
    var b = document.createElement('button');
    b.type = 'button';
    b.setAttribute('data-kag3-menu', label);
    b.textContent = label;
    b.style.cssText = 'display:block;width:100%;margin:6px 0;padding:10px 14px;' +
      'border-radius:8px;cursor:pointer;font:inherit;' +
      'border:1px solid rgba(255,255,255,.35);' +
      (primary ? 'background:rgba(255,255,255,.16);color:#fff;'
               : 'background:rgba(255,255,255,.06);color:#fff;');
    b.addEventListener('click', function (e) {
      e.preventDefault();
      e.stopPropagation();
      fn();
    });
    box.appendChild(b);
    return b;
  };
  if (tj.storage) {
    // Same semantics as the game's own return-to-title code
    // ([jump storage=first.ks target=*start]): a full process() switch, so the
    // pending frames of the abandoned scene must be dropped.
    add('回到主页菜单', function () {
      __kag3_menu_close();
      try {
        ['call', 'macro', 'if'].forEach(function (n) {
          if (kag.stat.stack && kag.stat.stack[n]) kag.stat.stack[n].length = 0;
        });
        kag.stat.is_skip = false;
        kag.stat.is_auto = false;
      } catch (e) {}
      __kag3_log('sysmenu -> title ' + tj.storage + ' ' + (tj.target || ''));
      __kag3_jump(kag, tj.storage, String(tj.target || '').replace(/^\*/, ''));
    }, true);
  }
  add('继续游戏', function () { __kag3_menu_close(); });
  var host = document.body || document.documentElement;
  if (!host) return;
  host.appendChild(box);
  __kag3_menu_el = box;
};
var __kag3_menu_toggle = function () {
  if (__kag3_menu_el) __kag3_menu_close(); else __kag3_menu_open();
};
// KAG3 [rclick] right-click handler. KAG3 fires the registered jump on
// right-click (comming/lineup screens, submenu back). Touch devices
// have no right-click, so a left click that is NOT on an active map
// region also triggers it while the flow is parked at [kag3stop].
// Plain [rclick enabled=true] (no jump) is the system-menu default:
// registered as null -> no-op (the port has no system menu overlay).
var __kag3_rclick = null;
// Last jump-rclick armed by the game that names a "*return_*" label.  That
// is the game's own back-to-gallery handler (e.g. seen_set.ks *return_seen:
// free layers, BGM_FS, jump seen.ks *seentop2); the replay-exit button
// reuses it because the game disarms rclick while a replay runs.
var __kag3_context_return = null;
var __kag3_exec_rclick = function () {
  var kag = window.TYRANO && TYRANO.kag;
  if (!kag || !__kag3_rclick) return;
  var r = __kag3_rclick;
  if (r.menu) { __kag3_menu_toggle(); return; }
  __kag3_rclick = null;
  __kag3_log('rclick -> ' + r.storage + ' ' + r.target);
  if (r.exp) { try { __kag3_run_body(r.exp, {}); } catch (e) {} }
  if (r.storage || r.target) __kag3_jump(kag, r.storage, r.target);
};
tyrano.plugin.kag.tag['rclick'] = {
  start: function (pm) {
    var enabled = String(pm.enabled === undefined ? true : pm.enabled) === 'true';
    var jump = String(pm.jump === undefined ? false : pm.jump) === 'true';
    var has_tgt = String(pm.storage || '') || String(pm.target || '');
    if (!enabled) {
      __kag3_rclick = null;
    } else if (!jump && !has_tgt) {
      // Plain [rclick enabled=true] is KAG3's built-in system menu.  Arm our own
      // overlay.  Right-click only (no left-click fallback): otherwise every
      // story click would open a menu.
      __kag3_rclick = { menu: true };
    } else {
      __kag3_rclick = { storage: pm.storage || '', target: pm.target || '', exp: pm.exp || '' };
      if (__kag3_rclick.storage && __kag3_rclick.target &&
          /return/i.test(String(__kag3_rclick.target))) {
        __kag3_context_return = {
          storage: __kag3_rclick.storage, target: __kag3_rclick.target,
        };
      }
    }
    this.kag.ftag.nextOrder();
  },
};
document.addEventListener('contextmenu', function (e) {
  if (!__kag3_rclick || __kag3_target_is_ui(e)) return;
  e.preventDefault();
  __kag3_exec_rclick();
}, true);
document.addEventListener('click', function (e) {
  // touch fallback: only when no map is active (maps own their clicks)
  if (!__kag3_rclick || __kag3_rclick.menu || __kag3_target_is_ui(e)) return;
  if (Object.keys(window.__kag3_maps || {}).length > 0) return;
  __kag3_exec_rclick();
}, true);
// Replay-exit action, exposed for the mobile control panel.  The game disarms
// its own right-click return while a replay runs ([rclick call=false
// jump=false enabled=true] at replay start), so a touch player has no way
// back to the gallery before the replay ends.  KAG3 rclick-jump = process():
// a full scenario switch, not a nested [call], so the abandoned replay frames
// must be dropped; the normal path also resets the two flags we skip
// (PV_START's now_pv=0 tail and seen_set.ks "sf.seenflg=0") - leaving them set
// would keep the button visible and hide the save/load buttons in the gallery
// (SYSMENU branches on seenflg).
var __kag3_exit_replay = function () {
  var kag = window.TYRANO && TYRANO.kag;
  if (!kag || !__kag3_context_return) return false;
  try {
    if (kag.stat && kag.stat.stack) {
      if (kag.stat.stack.call) kag.stat.stack.call.length = 0;
      if (kag.stat.stack.macro) kag.stat.stack.macro.length = 0;
      if (kag.stat.stack.if) kag.stat.stack.if.length = 0;
    }
  } catch (e1) {}
  try {
    kag.variable.tf.now_pv = 0;
    kag.variable.sf.seenflg = 0;
  } catch (e3) {}
  try {
    __kag3_jump(kag, __kag3_context_return.storage, __kag3_context_return.target);
  } catch (e2) {}
  return true;
};
// True while a replay is running AND the game has registered a *return_* label
// to go back to - the only situation where an exit action makes sense.
var __kag3_exit_available = function () {
  var kag = window.TYRANO && TYRANO.kag;
  return !!(kag && kag.variable && kag.variable.tf &&
            kag.variable.tf.now_pv == 1 && __kag3_context_return);
};
// Experimental bare message style (converter --msg-style bare): drop every
// backing plate (the story window on message0 *and* the name plate on
// message1) and let the text carry an outline + shadow.  The name plate is
// part of the same art set, so leaving it framed next to plate-less dialogue
// looked inconsistent (owner request).
if (window.__kag3_msg_style === 'bare') {
  (function () {
    var s = document.createElement('style');
    s.setAttribute('data-kag3', 'msg-bare');
    // The plate is NOT a style on the layer div: [position frame=...] puts the
    // backing image on the message layer's *inner* .message_outer element
    // (kag.tag.js:3208 j_message_outer.css("background-image", ...), same for
    // the frame colour), so the inner element is what has to lose its backing.
    // The layer-level rule stays for backings set on the layer itself.  Do NOT
    // hide <img> children: the message layers also hold the engine's "click to
    // continue" cue (system/nextpage.gif, .img_next) and a game can draw
    // faces/inline images into the same layer.
    s.textContent =
      "div[class*='message0'],div[class*='message1']{background:transparent !important;" +
      "background-image:none !important;}" +
      "div[class*='message0'] .message_outer," +
      "div[class*='message1'] .message_outer," +
      "div[class*='message0'] .message_inner," +
      "div[class*='message1'] .message_inner{background:transparent !important;" +
      "background-image:none !important;}" +
      // The shim's own default window dressing (runtime_shim.js: a translucent
      // plate + a big drop shadow on .kag3-dialog-frame/.kag3-name-frame) must
      // go as well, or "remove the plate" still leaves the shadow -- owner:
      // "底衬好像没删除干净，我还是能看出有阴影".  #tyrano_base raises the
      // specificity above the default rules.
      "#tyrano_base .message_outer.kag3-dialog-frame," +
      "#tyrano_base .message_outer.kag3-name-frame" +
      "{background:none !important;background-image:none !important;" +
      "border:0 !important;box-shadow:none !important}" +
      "div[class*='message0'] .message_text .inner," +
      "div[class*='message0'] .message_text_inner," +
      "div[class*='message0'] .message_text," +
      "div[class*='message1'] .message_text," +
      "div[class*='message1'] .name{-webkit-text-stroke:1px rgba(0,0,0,.35);}" +
      "div[class*='message0'] .message_text .inner span," +
      "div[class*='message0'] .message_text span," +
      "div[class*='message0'] .message_text," +
      "div[class*='message1'] .message_text span," +
      "div[class*='message1'] .message_text{text-shadow:0 1px 3px rgba(0,0,0,.85),0 0 2px rgba(0,0,0,.7);}" +
      "div[class*='message0'] .message_text{opacity:.8;}";
    var add = function () { document.head.appendChild(s); };
    if (document.head) add();
    else document.addEventListener('DOMContentLoaded', add);
  })();
}
  var apply_runtime = function () {
    var kag = window.TYRANO && TYRANO.kag;
    if (!kag || !kag.ftag || !kag.ftag.master_tag) return false;
    if (window.__kag3_runtime_applied) return true;
    window.__kag3_runtime_applied = true;
    try {
      // KAG3 can request far more foreground layers than Tyrano creates
      // from Config.tjs. Gallery grids depend on those numeric layers.
      var laycount = kag.ftag.master_tag.laycount;
      if (laycount && !laycount.__kag3_real) {
        laycount.__kag3_real = true;
        laycount.start = function (pm) {
          var count = Math.max(0, parseInt(pm.layers, 10) || 0);
          for (var i = 0; i < count; i++) {
            if (!kag.layer.map_layer_fore[String(i)]) kag.layer.addLayer(String(i));
          }
          kag.ftag.nextOrder();
        };
      }
      // Tyrano's stock conditional search stops after 2000 tags. Large
      // generated gallery blocks can legitimately exceed that distance.
      if (!kag.ftag.__kag3_long_tag_search) {
        kag.ftag.__kag3_long_tag_search = true;
        kag.ftag.nextOrderWithTagSearch = function (targetTags) {
          var remaining = this.array_tag.length - this.current_order_index;
          for (var i = 0; i < remaining; i++) {
            if (this.current_order_index >= this.array_tag.length - 1) break;
            if (this.nextOrderWithTag(targetTags)) return true;
          }
          return false;
        };
      }
      // Link jumps start before a bubbling document click handler runs.
      // Clear an outgoing choice at the next text render so the target
      // dialogue always receives a fresh paragraph and current span.
      window.__kag3_prepare_message = function (ownerKag) {
        var $inner = ownerKag.getMessageInnerLayer();
        if (!$inner.length || $inner.attr('data-kag3-choice-exiting') !== '1') return;
        $inner.removeAttr('data-kag3-choice-exiting').removeClass('kag3-choice');
        $inner.closest('.layer').removeClass('kag3-choice-layer');
        $inner.find('.kag3-choice-item,.kag3-choice-prompt,.kag3-choice-gap').remove();
        ownerKag.setNewParagraph($inner);
      };
      var textTag = kag.ftag.master_tag.text;
      if (textTag && textTag.start && !textTag.__kag3_choice_safe) {
        textTag.__kag3_choice_safe = true;
        var originalTextStart = textTag.start;
        textTag.start = function (pm) {
          window.__kag3_prepare_message(kag);
          return originalTextStart.call(this, pm);
        };
      }
      // KAG3 storage resolution: extensionless storages (bgm001,
      // yuki_title, macro params like %bmp) resolve against the
      // converted asset tree via the emitted __kag3_assets map (exact
      // on-disk case, subdirectory paths). Tyrano never appends an
      // extension, so resolve before the tag runs.
      //
      // Every asset now exists in exactly ONE place, so the resolved
      // value is `../<canonical_dir>/<file>`: the browser normalises the
      // dot segment (measured: ./data/image/../bgimage/x.png arrives as
      // /data/bgimage/x.png), so any tag finds it whichever
      // data/<folder>/ it prepends - including engine code that
      // concatenates the folder by hand.
      var __kag3_asset_path = function (s) {
        if (!s) return s;
        var t = String(s);
        if (t.indexOf('http') === 0 ||
            t.charAt(0) === '/' || t.indexOf('../') === 0) return s;
        var key = t.toLowerCase();
        var r = __kag3_assets()[key];
        // KAG3 animation plugins commonly prefix a still-image key with
        // `a` (for example afoo -> foo). The plugin data itself is not a
        // browser image. When its representative frame survived the asset
        // conversion, show that frame instead of leaving the gallery black.
        if (!r && key.charAt(0) === 'a') r = __kag3_assets()[key.slice(1)];
        return r ? '../' + r : s;
      };
      // Expose it: the generated KAG3-tag shim is a separate script and needs
      // the same resolver for [position frame=..] and [button graphic=..].
      window.__kag3_asset_path = __kag3_asset_path;
      var _resolve_storage = function (pm) {
        if (!pm) return pm;
        var s = pm.storage ? String(pm.storage) : '';
        var r = __kag3_asset_path(s);
        if (r !== s) {
          pm.storage = r;
          __kag3_log('storage ' + s + ' -> ' + r);
        }
        return pm;
      };
      // One hook on the dispatcher covers EVERY tag, including ones this
      // build does not know about and macro-generated calls; a per-tag
      // list would silently miss the next storage-bearing tag.
      if (!kag.ftag.__kag3_dispatcher_hooked) {
        kag.ftag.__kag3_dispatcher_hooked = true;
        var _start_tag = kag.ftag.startTag;
        kag.ftag.startTag = function (name, pm) {
          try {
            if (pm && typeof pm === 'object') {
              pm = _resolve_storage(pm) || pm;
              if (pm.graphic) {
                var g = __kag3_asset_path(pm.graphic);
                if (g !== pm.graphic) pm.graphic = g;
              }
            }
          } catch (e) {}
          return _start_tag.apply(this, arguments);
        };
      }
      var _wrap_storage = function (tag) {
        var t = kag.ftag.master_tag[tag];
        if (!t || !t.start) return;
        var orig = t.start;
        t.start = function (pm) {
          pm = _resolve_storage(pm) || pm;
          return orig.call(this, pm);
        };
      };
      // KAG3 loadImages semantics: ANY image load on a layer clears
      // the layer's clickable map, then X.ma + X_p.png are auto-attached
      // when present (GraphicLayer.tjs). [image]/[bg]/[bg2]/[graph] all
      // go through loadImages. The map survives scenario jumps/process()
      // (MainWindow.tjs process() never touches it) and is only removed
      // by a new image on the same layer or an explicit [mapdisable].
      ['image', 'bg', 'bg2', 'graph'].forEach(function (tag) {
        var _img = kag.ftag.master_tag[tag];
        if (!_img || !_img.start) return;
        var _imgs = _img.start;
        _img.start = function (pm) {
          var layerName = String(pm.layer || 'base');
          var before = String(pm.storage || '');
          pm = _resolve_storage(pm) || pm;
          __kag3_map_clear(layerName);
          var base = __kag3_stem(pm.storage);
          var maRel = __kag3_assets_ma()[base];
          if (maRel) {
            var text = __kag3_fetch_text(maRel);
            var actions = text === null ? {} : __kag3_parse_ma(text);
            var map = __kag3_map_set(layerName, actions, maRel);
            var reg = __kag3_assets()[base + '_p'];
            __kag3_log('imgload ' + tag + ' ' + before + ' -> ' + pm.storage + ' on ' + layerName +
                       (maRel ? ' (auto-map ' + maRel + ', region ' + (reg || '-') + ')' : ''));
            if (reg) __kag3_region_load(map, reg);
            __kag3_hook_input();
          } else {
            __kag3_log('imgload ' + tag + ' ' + before + ' -> ' + pm.storage + ' on ' + layerName);
          }
          return _imgs.call(this, pm);
        };
      });
      _wrap_storage('graph');
      _wrap_storage('ptext');
      _wrap_storage('chara_show');
      _wrap_storage('chara_mod');
      _wrap_storage('chara_ptext');
      _wrap_storage('playse');
      _wrap_storage('playbgm');
      // KAG3 replay semantics: a replay's opening [BGM] must take effect even
      // when it names the track that is already playing - several scene
      // entries reuse the gallery/menu track (e.g. [BGM bgm="bgm010"]).
      // Tyrano skips a same-storage [playbgm], which let the menu music run
      // seamlessly through the whole replay (owner-reported: "背景音还是菜单
      // 的音乐").  Clear the engine's current-bgm mark in replay mode so the
      // track restarts from 0:00 like a fresh KAG3 [playbgm].  Storage forms
      // differ (bare name vs resolved ../bgm/x.ogg), hence the stem compare;
      // [playse] passes target=se and must not be touched.
      // KAG3 keeps a single BGM slot: the fading track is still that slot, so
      // the next [playbgm] cuts it dead.  Tyrano instead deletes the howl from
      // kag.tmp.map_bgm[buf] *before* fading it out (kag.tag_audio.js stopbgm:
      // "delete target_map[key]" then audio_obj.fade(...)), so when the next
      // [playbgm] runs its case "bgm" finds an empty slot, stops nothing, and
      // the outgoing track keeps fading for the whole time (~3 s) underneath
      // the new one - audible doubling at every transition (measured: two
      // howls playing at once, old volume .70 -> .47 while the new sits at 1).
      // Capture the howl the engine is about to untrack and stop it on the
      // next BG start.  Capturing the object (not a name) means SE/voice howls
      // can never be caught by mistake.
      var __kag3_fading_howls = [];
      (function () {
        var _sb = kag.ftag.master_tag.stopbgm;
        if (_sb && _sb.start && !_sb.__kag3_track_fade) {
          var _sb_orig = _sb.start;
          _sb.__kag3_track_fade = true;
          _sb.start = function (pm) {
            try {
              // [fadeoutbgm] delegates here with fadeout=true, so this one hook
              // covers both spellings.  Only the bgm slot map is inspected:
              // [stopse]/[fadeoutse] arrive with target=se and must never be
              // remembered as a fading BGM, or the next [playbgm] would stop a
              // perfectly healthy SE.
              if (String((pm && pm.fadeout) || '') === 'true' &&
                  String((pm && pm.target) || 'bgm') === 'bgm') {
                var map = kag.tmp.map_bgm || {};
                var keys;
                if (String((pm && pm.buf_all) || 'false') === 'true') {
                  keys = Object.keys(map);
                } else {
                  keys = [String((pm && pm.buf) || '0')];
                }
                for (var i = 0; i < keys.length; i++) {
                  var h = map[keys[i]];
                  if (h) {
                    __kag3_fading_howls.push(h);
                    if (__kag3_fading_howls.length > 8) __kag3_fading_howls.shift();
                  }
                }
              }
            } catch (e) {}
            return _sb_orig.apply(this, arguments);
          };
        }
      })();
      (function () {
        var _pb = kag.ftag.master_tag.playbgm;
        if (!_pb || !_pb.start || _pb.__kag3_pv_restart) return;
        var _orig = _pb.start;
        _pb.__kag3_pv_restart = true;
        _pb.start = function (pm) {
          var __is_se = String((pm && pm.target) || 'bgm') === 'se';
          // Any new BGM cuts the faded-out leftovers (single-slot semantics).
          // A [stopbgm]-only path just lets the fade finish: nothing calls
          // this hook for it.  No BGM follows = no cut, so the game's own
          // fade timing is preserved everywhere else.
          if (!__is_se && __kag3_fading_howls.length) {
            while (__kag3_fading_howls.length) {
              var __h = __kag3_fading_howls.pop();
              try {
                if (__h && __h.playing && __h.playing()) {
                  __h.stop();
                  __h.unload();
                  __kag3_log('bgm fade cut: fading track stopped for a new bgm');
                }
              } catch (e) {}
            }
          }
          try {
            if (!__is_se &&
                kag.variable.tf && kag.variable.tf.now_pv == 1 &&
                kag.stat.current_bgm) {
              var stem = function (s) {
                return String(s == null ? '' : s).replace(/^.*[\\/]/, '')
                  .replace(/\.[^.]+$/, '').toLowerCase();
              };
              if (stem(pm && pm.storage) === stem(kag.stat.current_bgm)) {
                kag.stat.current_bgm = '';
                __kag3_log('pv bgm restart: ' + (pm && pm.storage));
              }
            }
          } catch (e) {}
          return _orig.apply(this, arguments);
        };
      })();
      // NOTE: no jump/call/return/link wrappers clear clickable maps.
      // KAG3 keeps the map alive across process()/jumps; scenarios
      // disable it explicitly with [mapdisable] (e.g. the title's
      // *game_start) or a new image load clears it (loadImages).
      // Tyrano draws [button] into the FREE layer, which sits ABOVE
      // .layer_event_click (z-index 999999 vs 9999) and spans the whole
      // canvas. Tyrano binds click-to-advance to .layer_event_click, so
      // while the free layer accepts pointer events every click targets
      // the free layer instead and a [p]/[s] click wait can never be
      // satisfied: the story looks frozen (no tag runs, no error,
      // nextOrder inert). The free layer must not intercept; its children
      // (the actual buttons) still must. A CSS rule covers layers created
      // after this script runs, so there is no initialisation ordering
      // race.
      (function () {
        try {
          var s = document.createElement('style');
          s.setAttribute('data-kag3', 'free-layer-clickthrough');
          s.textContent =
            // Numeric foreground containers are full-canvas elements.
            // Tyrano leaves even hidden and empty layers hit-testable, so
            // they can sit above .layer_event_click and make [s]/[p] waits
            // look frozen. The layer is decorative; images and other real
            // children remain interactive for document-level KAG3 maps.
            '.layer_fore{pointer-events:none !important}' +
            '.layer_fore>*{pointer-events:auto !important}' +
            '.layer_free{pointer-events:none !important}' +
            '.layer_free>*{pointer-events:auto !important}' +
            // Message layers must stack ABOVE the character layers, exactly
            // as in KAG3 (where layer numbers decide). Tyrano stacks by DOM
            // order instead, so a sprite layer could end up with a larger
            // z-index than the message window and paint over the dialogue
            // (measured: sprite layer z=4000 over .message_inner z=1001).
            // Message geometry stays source-driven; the classified frame
            // classes below replace desktop frame art with a mobile surface.
            // The dialogue text lives in messageN_BACK, not _fore (measured
            // chain: .message_inner -> .message0_back -> root_layer_game),
            // while the sprite layers carry z-index 3000/4000/5000 from their
            // KAG3 layer numbers, so every message page must outrank them.
            '#tyrano_base div[class*="message"][class*="_fore"],' +
            '#tyrano_base div[class*="message"][class*="_back"]' +
            '{z-index:8000 !important}' +
            // Message LAYERS must not steal clicks: giving every page the same
            // z-index erased the KAG3 order between them, so a later page
            // (measured: message13_fore) sat above the choice items and swallowed
            // every click aimed at them -- the first option could not be chosen.
            // The layer itself is decoration; its content must still receive
            // clicks, hence pointer-events:auto on the children.
            '#tyrano_base div[class*="message"][class*="_fore"],' +
            '#tyrano_base div[class*="message"][class*="_back"]' +
            '{pointer-events:none !important}' +
            '#tyrano_base div[class*="message"][class*="_fore"] *,' +
            '#tyrano_base div[class*="message"][class*="_back"] *' +
            '{pointer-events:auto !important}' +
            // Tyrano's stock round menu overlaps the bottom-right of the game.
            // The compact panel below replaces it with one consistent control.
            'img[src$="/button_menu.png"],img[src$="button_menu.png"]' +
            '{display:none !important}' +
            '.message_outer.kag3-dialog-frame{' +
            'background-image:none !important;background:rgba(5,8,14,.78) !important;' +
            'border:0 !important;' +
            'box-shadow:0 -14px 34px rgba(0,0,0,.48),inset 0 1px 0 rgba(255,255,255,.08)}' +
            '.message_inner.kag3-dialog-text{' +
            'padding:18px 40px 16px !important;line-height:1.5 !important;' +
            'text-shadow:0 2px 4px rgba(0,0,0,.95)}' +
            '.message_outer.kag3-name-frame{' +
            'left:0 !important;width:100% !important;box-sizing:border-box;' +
            'background-image:none !important;background:rgba(5,8,14,.78) !important;' +
            'border:0 !important;border-top:1px solid rgba(255,255,255,.32) !important;' +
            'border-radius:0 !important;box-shadow:0 -10px 26px rgba(0,0,0,.4)}' +
            '.message_inner.kag3-name-text{' +
            'left:0 !important;padding:0 40px !important;text-align:left !important;' +
            'text-shadow:0 2px 3px rgba(0,0,0,.95)}' +
            '.message_outer.kag3-aux-frame,.message_inner.kag3-aux-text{' +
            'display:none !important}' +
            // Text must never paint outside its window: Tyrano's default
            // line box is taller than KAG3's, so a long KAG3 message
            // can grow past the window and cover the bottom-right system
            // buttons. Clipping is the hard guarantee; __kag3_fit_message
            // below only reports an overflow (it never resizes text).
            '.message_inner{overflow:hidden}' +
            // [ch]-composed messages (choice lists, name plates) must not be
            // clipped: the game lays choice items out across more room than the
            // dialogue window (measured 113px window vs items 80px apart, so the
            // tail vanished -- owner: "选项文字消失了"). Normal dialogue keeps
            // the hard clip.
            '.message_inner.kag3ch-msg{overflow:visible !important}' +
            // Choice content gets an independent panel instead of inheriting
            // a short dialogue frame that cannot contain all visible rows.
            '.kag3-choice-layer .message_outer{display:none !important}' +
            '.message_inner.kag3-choice{' +
            'left:18% !important;top:16% !important;width:64% !important;' +
            'height:auto !important;min-height:0 !important;padding:22px 26px !important;' +
            'overflow:visible !important;background:rgba(5,8,14,.88);' +
            'border:1px solid rgba(255,255,255,.5);border-radius:12px;' +
            'box-shadow:0 16px 44px rgba(0,0,0,.58);text-align:left !important}' +
            '.message_inner.kag3-choice p{position:static !important;margin:0 !important;' +
            'padding:0 !important;line-height:1.35 !important}' +
            '.message_inner.kag3-choice .kag3-choice-prompt{' +
            // Left, not centred: the source macros lay the choice rows out left
            // ([position ...][style align=left][locate x=-30 y=5][ch]) and the
            // hard-centred prompt read as "the options are centred"
            // (owner: "理论上选项也应该是左对齐").
            'display:block;margin:0 0 14px;text-align:left;color:#fff}' +
            '.message_inner.kag3-choice .kag3-choice-gap{' +
            'display:none !important}' +
            '.message_inner.kag3-choice .kag3-choice-item{' +
            'display:block;margin:5px 0;padding:9px 15px;box-sizing:border-box;' +
            'border:1px solid rgba(255,255,255,.34);border-radius:8px;' +
            'background:rgba(255,255,255,.09);text-decoration:none;' +
            'color:#fff !important;text-shadow:0 2px 4px rgba(0,0,0,.95);cursor:pointer}' +
            '.message_inner.kag3-choice .kag3-choice-item span{' +
            'color:#fff !important}' +
            '.message_inner.kag3-choice .kag3-choice-item>img{' +
            'display:none !important}' +
            '.message_inner.kag3-choice .kag3-choice-item:hover,' +
            '.message_inner.kag3-choice .kag3-choice-item:focus{' +
            'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.75);' +
            'outline:none}' +
            // Keep source font sizes and native window margins, including nameplates.
            '.message_inner p.kag3ch{margin:0 !important;padding:0 !important}';
          (document.head || document.documentElement).appendChild(s);
        } catch (e) {}
      })();
      // ---- message text stays inside its window ----------------------
      // KAG3 sets a tight line height; Tyrano's default (about 1.6em) is
      // taller, so the same message can outgrow the window.
      //
      // Earlier this shrank the font until the text fit. That was wrong: the
      // sizes came out uneven between messages (reported as "字体忽大忽小很
      // 难看") and the real cause was that Tyrano's message text is simply
      // LARGER than the original's, so fewer characters fit per line. The fix
      // is to use the game's own metrics (KAG3 Config.tjs: defaultFontSize 22,
      // defaultLineSpacing 6 -> about 22px/28px), which makes the wrap points
      // match the original and the text fit with no rescaling at all.
      window.__kag3_fit_message = function (el) {
        try {
          if (!el || !el.clientHeight) return false;
          // Only report; never resize. overflow:hidden stays as the hard guard.
          return el.scrollHeight > el.clientHeight + 1;
        } catch (e) { return false; }      };
      // Fire on any DOM change but only run after the text settles: the
      // typewriter rewrites the message every frame, and measuring there
      // would force a layout per frame.
      (function () {
        try {
          var t = null;
          var run = function () {
            t = null;
            $('.message_inner').each(function () { window.__kag3_fit_message(this); });
          };
          new MutationObserver(function () {
            if (t) clearTimeout(t);
            t = setTimeout(run, 150);
          }).observe(document.body, { childList: true, subtree: true, characterData: true });
        } catch (e) {}
      })();
      // KAG3 [button graphic=X] art lives in bgimage/fgimage; the
      // dispatcher hook above already resolved pm.graphic to
      // '../<dir>/<file>' through the asset map. Do not resolve it a
      // second time here: assigning the bare map value made Tyrano
      // prepend its own folder and request
      // ./data/image/bgimage/x.png (measured 404 on every system button).
      var _btn = kag.ftag.master_tag && kag.ftag.master_tag.button;
      if (_btn && _btn.start) {
        var _btns = _btn.start;
        _btn.start = function (pm) {
          // Safety net for graphics whose name is built at runtime
          // (graphic="&tf.x"): the conversion-time rewrite cannot see
          // those. Delegates to the very same resolver as the dispatcher
          // hook, so the asset-map lookup has one implementation.
          if (pm && pm.graphic) {
            var _g = __kag3_asset_path(pm.graphic);
            if (_g !== pm.graphic) pm.graphic = _g;
          }
          // KAG3 '[current layer=messageN][locate x=0 y=0][button]'
          // anchors the button at the message area origin; Tyrano puts
          // free-layer buttons at locate (0,0) -> every system button
          // stacked at the top-left corner. Anchor to the current
          // message layer's outer frame when no explicit x/y is given.
          // The outer is already portrait-remapped by the [position]
          // wrapper, so anchored buttons must NOT be scaled again.
          var _anchored = false;
          if ((pm.x === undefined || pm.x === '') &&
              (pm.y === undefined || pm.y === '')) {
            var cl = this.kag.stat.current_layer;
            if (cl && String(cl).indexOf('message') === 0) {
              var _outer = this.kag.layer.getLayer(cl, this.kag.stat.current_page || 'fore').find('.message_outer');
              var _ol = parseInt(_outer.css('left'), 10) || 0;
              var _ot = parseInt(_outer.css('top'), 10) || 0;
              var _lx = parseInt(this.kag.stat.locate.x, 10) || 0;
              var _ly = parseInt(this.kag.stat.locate.y, 10) || 0;
              pm.x = String(_ol + _lx);
              pm.y = String(_ot + _ly);
              _anchored = true;
            }
          }
          if (window.__kag3_portrait && !_anchored) {
            // explicit x/y live in the 1024x768 art space; the free
            // layer is unscaled, so scale them to match the canvas
            if (pm.x !== undefined && pm.x !== '') pm.x = String(Math.round(parseInt(pm.x, 10) * 0.75));
            if (pm.y !== undefined && pm.y !== '') pm.y = String(Math.round(parseInt(pm.y, 10) * 0.75));
          }
          return _btns.call(this, pm);
        };
      }
      // embScript (used by [if]/[button exp]/[emb]) has no TG in scope;
      // expose it globally so the kag.->TG. rewrite works everywhere.
      window.TG = kag;
      // KAG3 [trans] may get layer=&sf.xxx which evaluates to undefined
      // when the init script has not run; Tyrano requires a layer value.
      var _tr = kag.ftag.master_tag && kag.ftag.master_tag.trans;
      if (_tr && _tr.start) {
        var _trs = _tr.start;
        _tr.start = function (pm) {
          if (pm && !pm.layer) pm.layer = 'base';
          __kag3_log('trans ' + (pm && pm.layer) + ' ' + (pm && pm.method) + ' ' + (pm && pm.time));
          return _trs.call(this, pm);
        };
      }
      var _wt = kag.ftag.master_tag && kag.ftag.master_tag.wt;
      if (_wt && _wt.start) {
        var _wts = _wt.start;
        _wt.start = function (pm) {
          if (pm && String(pm.canskip) === 'true' && kag.stat.is_trans) {
            // KAG3 [wt canskip=true]: a click skips the wait for the
            // transition to finish. Disarmed on trans completion so
            // the click never double-advances.
            var done = false;
            var finish = function () {
              if (done) return;
              done = true;
              try { kag.off('click-event.kag3wtskip'); } catch (e) {}
              kag.cancelWeakStop();
              kag.ftag.nextOrder();
            };
            kag.on('click-event.kag3wtskip', finish);
            kag.tmp.__kag3_wt_skip = finish;
            // Tyrano hides the event layer on every nextOrder; without
            // it the click never reaches j_event_layer and click-event
            // never fires, so the skip never triggers.
            try { kag.layer.showEventLayer(); } catch (e) {}
            __kag3_log('wt canskip: click-skips armed');
          }
          return _wts.call(this, pm);
        };
      }
      var _ct = kag.ftag && kag.ftag.completeTrans;
      if (_ct) {
        kag.ftag.completeTrans = function () {
          __kag3_log('trans complete (is_stop=' + kag.stat.is_stop + ')');
          if (kag.tmp && kag.tmp.__kag3_wt_skip) {
            var _f = kag.tmp.__kag3_wt_skip;
            kag.tmp.__kag3_wt_skip = null;
            try { kag.off('click-event.kag3wtskip'); } catch (e) {}
          }
          return _ct.apply(this, arguments);
        };
      }
      // KAG3 variable semantics: f/sf/tf/mp missing keys read as ''
      // (KAG3 scripts universally test f.xxx=='' for unset values;
      // Tyrano returns undefined which fails those tests - e.g. the
      // FAID_IN_T macro's mp.sepia check would skip image loads).
      // evalScript ([eval]/[iscript]) and embScript ([if]/[emb]/exp)
      // both get proxied scopes; kag.->TG. rewriting is folded in.
      // Portrait mode (--portrait): remap message windows from the
      // 1024x768 art grid into the 768x1024 portrait canvas. Text
      // windows (message0/1: dialogue, choices) scale x to 768 and
      // shift y down into the bottom black area (image area is 768x576);
      // other message layers (scene UI icons) ride the scaled art.
      if (window.__kag3_portrait) {
        var _pos = kag.ftag.master_tag && kag.ftag.master_tag.position;
        if (_pos && _pos.start) {
          var _poss = _pos.start;
          _pos.start = function (pm) {
            var lname = pm && pm.layer ? String(pm.layer) : '';
            if (lname.indexOf('message') === 0 && pm.left !== '' && pm.top !== '') {
              var L = parseInt(pm.left, 10) || 0;
              var T = parseInt(pm.top, 10) || 0;
              if (lname === 'message0' || lname === 'message1') {
                pm.left = Math.round(L * 0.75);
                if (pm.width !== '') pm.width = Math.round((parseInt(pm.width, 10) || 0) * 0.75);
                pm.top = T + 256;
                __kag3_log('portrait pos ' + lname + ' -> ' + pm.left + ',' + pm.top);
              } else {
                pm.left = Math.round(L * 0.75);
                if (pm.width !== '') pm.width = Math.round((parseInt(pm.width, 10) || 0) * 0.75);
                pm.top = Math.round(T * 0.75);
                if (pm.height !== '') pm.height = Math.round((parseInt(pm.height, 10) || 0) * 0.75);
              }
            }
            return _poss.call(this, pm);
          };
        }
      }
      if (kag.evalScript) {
        kag.evalScript = (function (orig) {
          return function (str) {
            var TG = this;
            var f = __kag3_proxy(this.stat.f);
            var sf = __kag3_proxy(this.variable.sf);
            var tf = __kag3_proxy(this.variable.tf);
            var mp = __kag3_proxy(this.stat.mp);
            try {
              eval(String(str).replace(/\bkag\./g, 'TG.'));
              this.saveSystemVariable();
            } catch (e) {
              console.error(e);
              try { this.warning(e, true); } catch (e2) {}
            }
          };
        })(kag.evalScript);
      }
      if (kag.embScript) {
        kag.embScript = (function (orig) {
          return function (str, preexp) {
            var TG = this;
            var f = __kag3_proxy(this.stat.f);
            var sf = __kag3_proxy(this.variable.sf);
            var tf = __kag3_proxy(this.variable.tf);
            var mp = __kag3_proxy(this.stat.mp);
            var src = String(str).replace(/\bkag\./g, 'TG.');
            try {
              return eval('(' + src + ')');
            } catch (e) {
              try { return eval(src); } catch (e2) { return undefined; }
            }
          };
        })(kag.embScript);
      }
      // KAG3 runtime: kag.n / kag.historyLayer (scenario code calls
      // kag.n.clear()), kag.se[] voice/sfx channels, runtime flags.
      var _hl = {
        clear: function () { return 0; },
        output: function () { return 0; },
      };
      kag.historyLayer = kag.historyLayer || _hl;
      kag.n = kag.n || _hl;
      // KAG3 SE channels. The game's voice/sound system drives playback from
      // iscript (`kag.se[0].play(%[storage:'vo_x'])`, `kag.se[0].status`,
      // `setOptions(%[gvolume:N])`), an API TyranoScript has no equivalent
      // for, so each channel is backed by a real HTMLAudioElement. The storage
      // resolves through the asset map, so extensionless KAG3 names (vo_xxx,
      // se003) still find their file. A stub here means SILENT voice, which is
      // exactly the defect this replaces.
      if (!kag.se) {
        var _se_make = function () {
          return {
            _el: null,
            _vol: 100,
            _loop: 0,
            status: 'stop',
            looping: 0,
            _apply: function () {
              if (!this._el) return;
              try { this._el.volume = Math.max(0, Math.min(1, this._vol / 100)); } catch (e) {}
              try { this._el.loop = !!this._loop; } catch (e) {}
            },
            setOptions: function (o) {
              if (o && o.gvolume !== undefined) this._vol = parseInt(o.gvolume, 10);
              if (o && o.loop !== undefined) { this._loop = parseInt(o.loop, 10) || 0; this.looping = this._loop; }
              this._apply();
              return this;
            },
            setVolume: function (v) { this._vol = parseInt(v, 10); this._apply(); return this; },
            play: function (o) {
              var st = o && o.storage !== undefined ? String(o.storage) : '';
              if (!st) return this;
              var am = __kag3_assets();
              var rel = am[__kag3_stem(st)] || am[st.toLowerCase()];
              var url = rel ? './data/' + rel : st;
              var self = this;
              try { if (this._el) { this._el.pause(); this._el.src = ''; } } catch (e) {}
              var el = new Audio(url);
              this._el = el;
              this._apply();
              el.addEventListener('ended', function () { if (self._el === el && !el.loop) { self.status = 'stop'; } });
              el.addEventListener('error', function () {
                if (self._el !== el) return;
                self.status = 'stop';
                __kag3_log('se error ' + url);
              });
              var pr = null;
              this.status = 'play';
              try { pr = el.play(); } catch (e) { this.status = 'stop'; }
              if (pr && pr.catch) { pr.catch(function () { if (self._el === el) self.status = 'stop'; }); }
              __kag3_log('se play ' + st + ' -> ' + url);
              return this;
            },
            stop: function () {
              try { if (this._el) { this._el.pause(); this._el.currentTime = 0; } } catch (e) {}
              this.status = 'stop';
              return this;
            },
          };
        };
        var _searr = [];
        for (var _i = 0; _i < 8; _i++) { _searr[_i] = _se_make(); }
        kag.se = _searr;
      }
      // KAG3 BGM object: only `playingStorage` is read by this game's scripts
      // (submenu/config), and the engine already tracks the current bgm.
      if (!kag.bgm) { kag.bgm = {}; }
      // KAG3 API called by the game's own UI. A missing method throws inside
      // the button's `exp`, so the button looks dead -- measured call sites:
      // skipToStop 10, showHistoryByKey 10, getBookMarkPageName 65,
      // getBookMarkDate 60, save/restore/storeBookMark 8, auto mode 4.
      if (!kag.skipToStop) {
        // KAG3: fast-forward until the next stop (a choice, or [s]).
        kag.skipToStop = function () {
          try { this.setSkip(true, {}); } catch (e) {}
          __kag3_log('skipToStop -> skip on');
          return true;
        };
      }
      var _kag3_stub = function (name, ret) {
        if (kag[name]) return;
        kag[name] = function () { __kag3_log('stub ' + name); return ret; };
      };
      // The bookmark display helpers feed the game's own save/load screens;
      // Tyrano keeps its own save data, so empty values keep those screens
      // from throwing while the engine's save menu does the work.
      _kag3_stub('getBookMarkPageName', '');
      _kag3_stub('getBookMarkDate', '');
      _kag3_stub('getBookMarkFileNameAtNum', '');
      if (!kag.showHistoryByKey) { kag.showHistoryByKey = function () { this.menu.displayLog(); return 1; }; }
      _kag3_stub('storeBookMark', 0);
      _kag3_stub('restoreBookMark', 0);
      _kag3_stub('saveBookMark', 0);
      if (!kag.goToStartWithAsk) { kag.goToStartWithAsk = function () { this.backTitle(); return 1; }; }
      // A desktop [close] terminates the browser window.  On JoiPlay it
      // must stay inside the game, so use Tyrano's return-to-title flow.
      var _close = kag.ftag.master_tag && kag.ftag.master_tag.close;
      if (_close && _close.start && !_close.__kag3_mobile) {
        _close.__kag3_mobile = true;
        _close.start = function () { kag.backTitle(); };
      }
      _kag3_stub('addPlugin', 0);
      if (!kag.enterAutoMode) { kag.enterAutoMode = function () { this.setAuto(true); this.autoMode = 1; return 1; }; }
      if (!kag.cancelAutoMode) { kag.cancelAutoMode = function () { this.setAuto(false); this.autoMode = 0; return 1; }; }
      // Compact touch controls for mobile builds. They call Tyrano's real
      // menu/state APIs and deliberately live outside scenario layers.
      if (!document.getElementById('kag3-mobile-panel')) {
        var panel = document.createElement('div');
        panel.id = 'kag3-mobile-panel';
        panel.innerHTML = '<button class=kag3-mobile-toggle data-kag3-action=toggle aria-label="Game controls">&#9776;</button>' +
          '<div class=kag3-mobile-actions>' +
          '<button data-kag3-action=save>SAVE</button><button data-kag3-action=load>LOAD</button>' +
          '<button data-kag3-action=log>LOG</button><button data-kag3-action=auto>AUTO</button>' +
          '<button data-kag3-action=skip>SKIP</button><button data-kag3-action=hide>HIDE</button>' +
          '<button data-kag3-action=menu>MENU</button>' +
          '<button data-kag3-action=gallery style="display:none">GALLERY</button></div>';
        panel.style.cssText = 'position:fixed;right:10px;top:10px;z-index:2147483000;' +
          'display:flex;gap:8px;align-items:flex-start;font:600 14px sans-serif;pointer-events:auto';
        var actions = panel.querySelector('.kag3-mobile-actions');
        actions.style.cssText = 'display:none;gap:6px;flex-wrap:wrap;justify-content:flex-end;' +
          'max-width:min(420px,82vw);padding:6px;border-radius:10px;background:rgba(4,7,12,.64);' +
          'box-shadow:0 8px 24px rgba(0,0,0,.35);backdrop-filter:blur(5px)';
        Array.prototype.forEach.call(panel.querySelectorAll('button'), function (b) {
          b.style.cssText = 'min-width:52px;min-height:44px;padding:6px 9px;color:white;' +
            'background:rgba(12,17,26,.9);border:1px solid rgba(255,255,255,.55);' +
            'border-radius:8px;box-shadow:0 4px 12px rgba(0,0,0,.25)';
        });
        panel.querySelector('.kag3-mobile-toggle').style.cssText +=
          ';min-width:46px;width:46px;font-size:24px;line-height:1';
        var sync = function () {
          var a = panel.querySelector('[data-kag3-action=auto]');
          var s = panel.querySelector('[data-kag3-action=skip]');
          if (a) a.setAttribute('aria-pressed', kag.stat.is_auto ? 'true' : 'false');
          if (s) s.setAttribute('aria-pressed', kag.stat.is_skip ? 'true' : 'false');
          // GALLERY (replay exit) only makes sense while a replay runs and the
          // game registered a *return_* label; it is part of this control row
          // so it can never overlap the menu key (owner-reported overlap when
          // it was a separate floating button).
          var g = panel.querySelector('[data-kag3-action=gallery]');
          if (g) g.style.display = __kag3_exit_available() ? '' : 'none';
        };
        // The replay can start without any panel interaction, so keep the
        // GALLERY entry in sync with the replay state.
        setInterval(sync, 500);
        var menuLayer = kag.layer.getMenuLayer();
        var menuPending = false;
        var menuIsVisible = function () {
          return menuLayer && menuLayer.css('display') !== 'none' && menuLayer.children().length > 0;
        };
        var syncMenuVisibility = function () {
          panel.style.visibility = menuIsVisible() ? 'hidden' : 'visible';
        };
        var menuObserver = new MutationObserver(syncMenuVisibility);
        if (menuLayer && menuLayer[0]) menuObserver.observe(menuLayer[0],
          {attributes:true,childList:true,subtree:false});
        var openMenu = function (method) {
          if (menuPending || menuIsVisible()) return;
          menuPending = true;
          actions.style.display = 'none';
          panel.style.visibility = 'hidden';
          menuLayer.stop(true, true).hide().empty();
          try { method(); } catch (err) {
            menuPending = false; syncMenuVisibility(); throw err;
          }
          setTimeout(function () { menuPending = false; syncMenuVisibility(); }, 750);
        };
        var runAction = function (b, e) {
          e.preventDefault(); e.stopPropagation();
          var a = b.getAttribute('data-kag3-action');
          try {
            if (a === 'toggle') actions.style.display = actions.style.display === 'none' ? 'flex' : 'none';
            else if (a === 'save') openMenu(function () { kag.menu.displaySave(); });
            else if (a === 'load') openMenu(function () { kag.menu.displayLoad(); });
            else if (a === 'log') openMenu(function () { kag.menu.displayLog(); });
            else if (a === 'auto') kag.setAuto(!kag.stat.is_auto);
            else if (a === 'skip') {
              if (kag.stat.is_skip) kag.setSkip(false);
              else if (kag.stat.is_adding_text) kag.setSkip(true);
              else kag.ftag.startTag('skipstart', {});
            }
            else if (a === 'menu') {
              // The game's own system menu (KAG3's [rclick] default) is not part
              // of the engine port, so this is where it lives.
              actions.style.display = 'none';
              __kag3_menu_toggle();
            }
            else if (a === 'gallery') {
              // Leave the replay through the game's own return handler.
              actions.style.display = 'none';
              __kag3_log('mobile panel: exit replay');
              __kag3_exit_replay();
            }
            else if (a === 'hide') {
              if (kag.stat.is_hide_message) {
                kag.layer.showMessageLayers();
                kag.stat.is_click_text = false;
                if (!kag.stat.is_strong_stop) kag.layer.showEventLayer('kag3-mobile-hide');
              } else {
                kag.setSkip(false);
                kag.ftag.startTag('hidemessage', {});
              }
            }
          } catch (err) { __kag3_log('mobile panel ' + a + ': ' + err); }
          sync();
        };
        window.addEventListener('click', function (e) {
          var b = e.target && e.target.closest ? e.target.closest('button') : null;
          if (b && panel.contains(b)) runAction(b, e);
        }, true);
        document.body.appendChild(panel);
        syncMenuVisibility();
        sync();
      }
      if (!window.__kag3_choice_cleanup) {
        window.__kag3_choice_cleanup = true;
        document.addEventListener('click', function (e) {
          var item = e.target && e.target.closest ? e.target.closest('.kag3-choice-item') : null;
          if (!item) return;
          var $owner = $(item).closest('.message_inner');
          var $layer = $owner.closest('.layer');
          var $old = $owner.find('.kag3-choice-item,.kag3-choice-prompt,.kag3-choice-gap');
          $owner.attr('data-kag3-choice-exiting', '1');
          setTimeout(function () {
            $old.remove();
            if (!$owner.find('.kag3-choice-item').length) {
              $owner.removeClass('kag3-choice');
              $layer.removeClass('kag3-choice-layer');
            }
          }, 0);
        }, true);
      }
      // Fast-forward must also pass HARD waits: the engine only drops waits
      // whose `skippable` is true ([wait canskip=false] / [wt] keep waiting),
      // so skipping stalled on every one of them. While skip is on, the wait
      // is dropped; normal playback is untouched.
      ['wait', 'wt', 'waittrig'].forEach(function (t) {
        var tag = kag.ftag.master_tag[t];
        if (!tag || !tag.start || tag.__kag3_fast) return;
        tag.__kag3_fast = true;
        var orig = tag.start;
        tag.start = function (pm) {
          if (kag.stat && kag.stat.is_skip) { return kag.ftag.nextOrder(); }
          return orig.call(this, pm);
        };
      });
      // KAG3 runtime flags read by iscript/eval
      kag.autoMode = kag.autoMode || 0;
      kag.clickWaiting = kag.clickWaiting || false;
      kag.transCount = kag.transCount || 0;
      kag.inStable = kag.inStable || 1;
      kag.stat = kag.stat || {};
      // KAG3 kag.process(storage, label): replace the current flow and
      // run from the label (used by map onenter/onleave and iscript).
      // Tyrano's nextOrderWithLabel strips a leading '*' itself.
      if (!kag.process) {
        kag.process = function (storage, target) {
          __kag3_jump(kag, storage, target);
        };
      }
      kag.callExtraConductor = kag.callExtraConductor || function () { return 0; };
      // KAG3 macros are expanded at parse time, so a `[return]` written inside a
      // macro body is just a plain tag in the caller's order stream: it returns
      // from the enclosing `[call]`.  Tyrano executes macros with a runtime frame
      // stack instead, and its own `[return]` resumes the *macro's* caller while
      // leaving that frame behind - the engine documents the limitation itself
      // (`kag.tag_system.js`: "だからmacro で return は使えない").
      //
      // Measured on a gallery replay: the replay scene ends with a macro whose
      // body is `[if exp="tf.now_pv == 1"][return][endif]`.  With the stock
      // engine the flow fell back into the story at the macro's caller line
      // (the gallery never returned, and the scene flag the cleanup code clears
      // stayed set); stamping the macro depth on each call-stack entry and
      // truncating it on `[return]` restores the KAG3 behaviour - frames opened
      // by the callee are dropped, the caller's own frames survive.
      if (!kag.__kag3_return_patched) {
        kag.__kag3_return_patched = true;
        var _macroDepthKey = '__kag3_macro_depth';
        var _pushStack = kag.pushStack;
        if (typeof _pushStack === 'function') {
          kag.pushStack = function (name, flag) {
            if (name === 'call' && flag && typeof flag === 'object') {
              try {
                flag[_macroDepthKey] = (kag.stat.stack.macro || []).length;
              } catch (e) {}
            }
            return _pushStack.apply(this, arguments);
          };
        }
        var _returnTag = kag.ftag.master_tag['return'];
        if (_returnTag && _returnTag.start) {
          var _returnStart = _returnTag.start;
          _returnTag.start = function (pm) {
            try {
              var top = kag.getStack('call');
              var frames = kag.stat.stack.macro;
              if (top && typeof top[_macroDepthKey] === 'number' && frames &&
                  frames.length > top[_macroDepthKey]) {
                var dropped = frames.length - top[_macroDepthKey];
                frames.length = top[_macroDepthKey];
                __kag3_log('return: dropped ' + dropped + ' macro frame(s) opened by the callee');
              }
            } catch (e) {}
            return _returnStart.apply(this, arguments);
          };
        }
      }
      // debug/UX hotkeys (KAG3 port niceties):
      //   Ctrl+Enter  jump to the next [select] tag in the current
      //               scenario (skip dialogue up to the next choice)
      //   Ctrl+S      toggle Tyrano skip mode
      if (!window.__kag3_hotkeys) {
        window.__kag3_hotkeys = true;
        document.addEventListener('keydown', function (e) {
          var kag = window.TYRANO && TYRANO.kag;
          if (!kag || !e.ctrlKey) return;
          if (e.key === 'Enter') {
            var arr = kag.ftag.array_tag || [];
            for (var i = kag.ftag.current_order_index + 1; i < arr.length; i++) {
              if (arr[i] && /^select(?:_|$)/.test(String(arr[i].name || '')) &&
                  !/(?:clear|off)$/.test(String(arr[i].name || ''))) {
                kag.ftag.nextOrderWithIndex(i, kag.stat.current_scenario);
                e.preventDefault();
                __kag3_log('hotkey: jump to next choice at index ' + i);
                return;
              }
            }
          }
          if (e.key === 's' || e.key === 'S') {
            var on = !kag.stat.is_skip;
            kag.setSkip(on, {});
            __kag3_log('hotkey: skip ' + (on ? 'ON' : 'OFF'));
            e.preventDefault();
          }
        });
      }
      // record unknown tags for debugging
      if (kag.error) {
        var orig = kag.error;
        kag.error = function (type, tag) {
          if (type === 'undefined_tag' && tag && tag.name) {
            window.__missing_tags.push(tag.name);
            var d = document.getElementById('__missing_tags');
            if (!d) { d = document.createElement('div'); d.id = '__missing_tags'; d.style.display = 'none'; document.body.appendChild(d); }
            d.textContent = window.__missing_tags.join(',');
          }
          return orig.apply(this, arguments);
        };
      }
      return true;
    } catch (e) {
      window.__kag3_runtime_applied = false;
      return false;
    }
  };
  if (!apply_runtime()) {
    var _t = setInterval(function () { if (apply_runtime()) clearInterval(_t); }, 200);
  }
})();
